#include "unity.h"

void test_zero_flag8_high_bit(void);
void test_zero_flag8_middle_bit(void);
void test_zero_flag8_nonzero(void);
void test_zero_flag8_zero(void);
void test_adder8_carry_across_nibble(void);
void test_adder8_carry_in_and_carry_out(void);
void test_adder8_carry_out(void);
void test_adder8_example_addition(void);
void test_adder8_pattern_addition(void);
void test_adder8_simple_addition(void);
void test_adder8_with_carry_in(void);
void test_adder8_zero(void);
void test_full_adder_one_one_one(void);
void test_full_adder_one_one_zero(void);
void test_full_adder_one_zero_one(void);
void test_full_adder_one_zero_zero(void);
void test_full_adder_zero_one_one(void);
void test_full_adder_zero_one_zero(void);
void test_full_adder_zero_zero_one(void);
void test_full_adder_zero_zero_zero(void);
void test_half_adder_one_one(void);
void test_half_adder_one_zero(void);
void test_half_adder_zero_one(void);
void test_half_adder_zero_zero(void);
void test_subtractor8_borrow(void);
void test_subtractor8_equal(void);
void test_subtractor8_simple(void);
void test_subtractor8_zero(void);
void test_address_map(void);
void test_alu_add(void);
void test_alu_add_carry(void);
void test_alu_add_no_carry(void);
void test_alu_add_overflow(void);
void test_alu_and(void);
void test_alu_and_partial(void);
void test_alu_negative_clear(void);
void test_alu_negative_set(void);
void test_alu_nonzero_flag(void);
void test_alu_or(void);
void test_alu_or_partial(void);
void test_alu_shl(void);
void test_alu_shl_overflow(void);
void test_alu_shr(void);
void test_alu_shr_overflow(void);
void test_alu_sub(void);
void test_alu_sub_borrow(void);
void test_alu_sub_no_borrow(void);
void test_alu_xor(void);
void test_alu_xor_partial(void);
void test_alu_zero_flag(void);
void test_flags_load(void);
void test_get_bit_clear_bit(void);
void test_get_bit_from_high_bit(void);
void test_get_bit_from_middle(void);
void test_get_bit_one(void);
void test_get_bit_zero(void);
void test_set_bit_can_clear_one_bit_without_affecting_others(void);
void test_set_bit_clears_set_bit(void);
void test_set_bit_does_not_change_other_bits(void);
void test_set_bit_sets_clear_bit(void);
void test_set_bit_sets_high_bit(void);
void test_bus_selects_source0(void);
void test_bus_selects_source1(void);
void test_bus_selects_source2(void);
void test_bus_selects_source3(void);
void test_bus_to_alu_to_bus(void);
void test_comparator_equal(void);
void test_comparator_greater(void);
void test_comparator_less(void);
void test_register_to_bus_to_register(void);
void test_decoder4to16(void);
void test_decoder_00(void);
void test_decoder_01(void);
void test_decoder_10(void);
void test_decoder_11(void);
void test_flags_init(void);
void test_flags_load_from_alu(void);
void test_flags_write_borrow(void);
void test_flags_write_carry(void);
void test_flags_write_negative(void);
void test_flags_write_overflow(void);
void test_flags_write_zero(void);
void test_increment_mux_selects_alternate(void);
void test_increment_mux_wraps_at_255(void);
void test_pc_increment_mux_selects_increment(void);
void test_logic_and(void);
void test_logic_and8(void);
void test_logic_equal_one_one(void);
void test_logic_equal_one_zero(void);
void test_logic_equal_zero_one(void);
void test_logic_equal_zero_zero(void);
void test_logic_greater(void);
void test_logic_less(void);
void test_logic_nand(void);
void test_logic_nand8(void);
void test_logic_nor(void);
void test_logic_not8(void);
void test_logic_not_one(void);
void test_logic_not_zero(void);
void test_logic_or(void);
void test_logic_or8(void);
void test_logic_xor(void);
void test_logic_xor8(void);
void test_mux16(void);
void test_mux4_select_a(void);
void test_mux4_select_b(void);
void test_mux4_select_c(void);
void test_mux4_select_d(void);
void test_mux_can_select_maximum_value(void);
void test_mux_can_select_zero(void);
void test_mux_inputs_are_independent(void);
void test_mux_selects_a_when_select_is_zero(void);
void test_mux_selects_b_when_select_is_one(void);
void test_negative_flag8_clear(void);
void test_negative_flag8_max(void);
void test_negative_flag8_set(void);
void test_alu_add_no_overflow(void);
void test_overflow_add8_negative(void);
void test_overflow_add8_no_overflow_negative(void);
void test_overflow_add8_no_overflow_positive(void);
void test_overflow_add8_positive(void);
void test_ram_destroy(void);
void test_ram_init(void);
void test_ram_write(void);
void test_register_can_store_maximum_value(void);
void test_register_can_store_value(void);
void test_register_initializes_to_zero(void);
void test_register_overwrites_previous_value(void);
void test_register_write_disabled(void);
void test_register_file_eight_registers(void);
void test_register_file_init(void);
void test_register_file_max_registers(void);
void test_register_file_one_register(void);
void test_register_file_registers_are_isolated(void);
void test_register_file_sixteen_registers(void);
void test_register_file_write_disabled(void);
void test_register_file_write_register0(void);
void test_register_file_write_register1(void);
void test_register_file_write_register2(void);
void test_register_file_write_register3(void);
void test_rom_copies_data(void);
void test_rom_destroy(void);
void test_rom_init(void);
void test_shift_left8(void);
void test_shift_left8_carry(void);
void test_shift_right8(void);
void test_shift_right8_carry(void);

void setUp(void)
{
}

void tearDown(void)
{
}

int main(void)
{
    UNITY_BEGIN();

    RUN_TEST(test_zero_flag8_high_bit);
    RUN_TEST(test_zero_flag8_middle_bit);
    RUN_TEST(test_zero_flag8_nonzero);
    RUN_TEST(test_zero_flag8_zero);
    RUN_TEST(test_adder8_carry_across_nibble);
    RUN_TEST(test_adder8_carry_in_and_carry_out);
    RUN_TEST(test_adder8_carry_out);
    RUN_TEST(test_adder8_example_addition);
    RUN_TEST(test_adder8_pattern_addition);
    RUN_TEST(test_adder8_simple_addition);
    RUN_TEST(test_adder8_with_carry_in);
    RUN_TEST(test_adder8_zero);
    RUN_TEST(test_full_adder_one_one_one);
    RUN_TEST(test_full_adder_one_one_zero);
    RUN_TEST(test_full_adder_one_zero_one);
    RUN_TEST(test_full_adder_one_zero_zero);
    RUN_TEST(test_full_adder_zero_one_one);
    RUN_TEST(test_full_adder_zero_one_zero);
    RUN_TEST(test_full_adder_zero_zero_one);
    RUN_TEST(test_full_adder_zero_zero_zero);
    RUN_TEST(test_half_adder_one_one);
    RUN_TEST(test_half_adder_one_zero);
    RUN_TEST(test_half_adder_zero_one);
    RUN_TEST(test_half_adder_zero_zero);
    RUN_TEST(test_subtractor8_borrow);
    RUN_TEST(test_subtractor8_equal);
    RUN_TEST(test_subtractor8_simple);
    RUN_TEST(test_subtractor8_zero);
    RUN_TEST(test_address_map);
    RUN_TEST(test_alu_add);
    RUN_TEST(test_alu_add_carry);
    RUN_TEST(test_alu_add_no_carry);
    RUN_TEST(test_alu_add_overflow);
    RUN_TEST(test_alu_and);
    RUN_TEST(test_alu_and_partial);
    RUN_TEST(test_alu_negative_clear);
    RUN_TEST(test_alu_negative_set);
    RUN_TEST(test_alu_nonzero_flag);
    RUN_TEST(test_alu_or);
    RUN_TEST(test_alu_or_partial);
    RUN_TEST(test_alu_shl);
    RUN_TEST(test_alu_shl_overflow);
    RUN_TEST(test_alu_shr);
    RUN_TEST(test_alu_shr_overflow);
    RUN_TEST(test_alu_sub);
    RUN_TEST(test_alu_sub_borrow);
    RUN_TEST(test_alu_sub_no_borrow);
    RUN_TEST(test_alu_xor);
    RUN_TEST(test_alu_xor_partial);
    RUN_TEST(test_alu_zero_flag);
    RUN_TEST(test_flags_load);
    RUN_TEST(test_get_bit_clear_bit);
    RUN_TEST(test_get_bit_from_high_bit);
    RUN_TEST(test_get_bit_from_middle);
    RUN_TEST(test_get_bit_one);
    RUN_TEST(test_get_bit_zero);
    RUN_TEST(test_set_bit_can_clear_one_bit_without_affecting_others);
    RUN_TEST(test_set_bit_clears_set_bit);
    RUN_TEST(test_set_bit_does_not_change_other_bits);
    RUN_TEST(test_set_bit_sets_clear_bit);
    RUN_TEST(test_set_bit_sets_high_bit);
    RUN_TEST(test_bus_selects_source0);
    RUN_TEST(test_bus_selects_source1);
    RUN_TEST(test_bus_selects_source2);
    RUN_TEST(test_bus_selects_source3);
    RUN_TEST(test_bus_to_alu_to_bus);
    RUN_TEST(test_comparator_equal);
    RUN_TEST(test_comparator_greater);
    RUN_TEST(test_comparator_less);
    RUN_TEST(test_register_to_bus_to_register);
    RUN_TEST(test_decoder4to16);
    RUN_TEST(test_decoder_00);
    RUN_TEST(test_decoder_01);
    RUN_TEST(test_decoder_10);
    RUN_TEST(test_decoder_11);
    RUN_TEST(test_flags_init);
    RUN_TEST(test_flags_load_from_alu);
    RUN_TEST(test_flags_write_borrow);
    RUN_TEST(test_flags_write_carry);
    RUN_TEST(test_flags_write_negative);
    RUN_TEST(test_flags_write_overflow);
    RUN_TEST(test_flags_write_zero);
    RUN_TEST(test_increment_mux_selects_alternate);
    RUN_TEST(test_increment_mux_wraps_at_255);
    RUN_TEST(test_pc_increment_mux_selects_increment);
    RUN_TEST(test_logic_and);
    RUN_TEST(test_logic_and8);
    RUN_TEST(test_logic_equal_one_one);
    RUN_TEST(test_logic_equal_one_zero);
    RUN_TEST(test_logic_equal_zero_one);
    RUN_TEST(test_logic_equal_zero_zero);
    RUN_TEST(test_logic_greater);
    RUN_TEST(test_logic_less);
    RUN_TEST(test_logic_nand);
    RUN_TEST(test_logic_nand8);
    RUN_TEST(test_logic_nor);
    RUN_TEST(test_logic_not8);
    RUN_TEST(test_logic_not_one);
    RUN_TEST(test_logic_not_zero);
    RUN_TEST(test_logic_or);
    RUN_TEST(test_logic_or8);
    RUN_TEST(test_logic_xor);
    RUN_TEST(test_logic_xor8);
    RUN_TEST(test_mux16);
    RUN_TEST(test_mux4_select_a);
    RUN_TEST(test_mux4_select_b);
    RUN_TEST(test_mux4_select_c);
    RUN_TEST(test_mux4_select_d);
    RUN_TEST(test_mux_can_select_maximum_value);
    RUN_TEST(test_mux_can_select_zero);
    RUN_TEST(test_mux_inputs_are_independent);
    RUN_TEST(test_mux_selects_a_when_select_is_zero);
    RUN_TEST(test_mux_selects_b_when_select_is_one);
    RUN_TEST(test_negative_flag8_clear);
    RUN_TEST(test_negative_flag8_max);
    RUN_TEST(test_negative_flag8_set);
    RUN_TEST(test_alu_add_no_overflow);
    RUN_TEST(test_overflow_add8_negative);
    RUN_TEST(test_overflow_add8_no_overflow_negative);
    RUN_TEST(test_overflow_add8_no_overflow_positive);
    RUN_TEST(test_overflow_add8_positive);
    RUN_TEST(test_ram_destroy);
    RUN_TEST(test_ram_init);
    RUN_TEST(test_ram_write);
    RUN_TEST(test_register_can_store_maximum_value);
    RUN_TEST(test_register_can_store_value);
    RUN_TEST(test_register_initializes_to_zero);
    RUN_TEST(test_register_overwrites_previous_value);
    RUN_TEST(test_register_write_disabled);
    RUN_TEST(test_register_file_eight_registers);
    RUN_TEST(test_register_file_init);
    RUN_TEST(test_register_file_max_registers);
    RUN_TEST(test_register_file_one_register);
    RUN_TEST(test_register_file_registers_are_isolated);
    RUN_TEST(test_register_file_sixteen_registers);
    RUN_TEST(test_register_file_write_disabled);
    RUN_TEST(test_register_file_write_register0);
    RUN_TEST(test_register_file_write_register1);
    RUN_TEST(test_register_file_write_register2);
    RUN_TEST(test_register_file_write_register3);
    RUN_TEST(test_rom_copies_data);
    RUN_TEST(test_rom_destroy);
    RUN_TEST(test_rom_init);
    RUN_TEST(test_shift_left8);
    RUN_TEST(test_shift_left8_carry);
    RUN_TEST(test_shift_right8);
    RUN_TEST(test_shift_right8_carry);

    return UNITY_END();
}
