import glob
import re
from pathlib import Path

TEST_DIR = "tests"
TEST_MAIN = "tests/generated_test_main.c"
TEST_REPORT = "docs/tests.md"


def discover_tests():
    tests = []

    for filename in glob.glob(f"{TEST_DIR}/**/*.c", recursive=True):
        if filename.endswith("generated_test_main.c"):
            continue

        with open(filename, "r") as file:
            source = file.read()

        matches = re.findall(
            r"\bvoid\s+(test_[a-zA-Z0-9_]+)\s*\(\s*void\s*\)",
            source
        )

        for test in matches:
            tests.append({
                "file": filename,
                "name": test
            })

    tests.sort(key=lambda test: (test["file"], test["name"]))

    return tests


def generate_test_main(tests):
    with open(TEST_MAIN, "w") as file:
        file.write('#include "unity.h"\n\n')

        for test in tests:
            file.write(f'void {test["name"]}(void);\n')

        file.write("\n")

        file.write("void setUp(void)\n")
        file.write("{\n")
        file.write("}\n\n")

        file.write("void tearDown(void)\n")
        file.write("{\n")
        file.write("}\n\n")

        file.write("int main(void)\n")
        file.write("{\n")
        file.write("    UNITY_BEGIN();\n\n")

        for test in tests:
            file.write(f'    RUN_TEST({test["name"]});\n')

        file.write("\n")
        file.write("    return UNITY_END();\n")
        file.write("}\n")


def category_name(filename):
    name = Path(filename).stem

    if name.startswith("test_"):
        name = name[5:]

    return name.replace("_", " ").title()


def generate_test_report(tests):
    Path("docs").mkdir(exist_ok=True)

    categories = {}

    for test in tests:
        categories.setdefault(test["file"], []).append(test["name"])

    total = len(tests)

    with open(TEST_REPORT, "w") as file:
        file.write("# Logic Complete Test Report\n\n")

        file.write(
            "<!-- This file is automatically generated. "
            "Do not edit manually. -->\n\n"
        )

        file.write("## Summary\n\n")

        file.write("<!-- TEST_SUMMARY_START -->\n")
        file.write("| Tests | Failures | Ignored | Warnings |\n")
        file.write("|---:|---:|---:|---:|\n")
        file.write("| — | — | — | — |\n")
        file.write("<!-- TEST_SUMMARY_END -->\n\n")

        file.write("---\n\n")

        for filename, category_tests in categories.items():
            file.write(f"## {category_name(filename)}\n\n")

            file.write("| Test | Result |\n")
            file.write("|---|---|\n")

            for test in category_tests:
                file.write(f"| `{test}` | 🟢 PASS |\n")

            count = len(category_tests)

            file.write(
                f"\n**{count} test"
                f"{'' if count == 1 else 's'} discovered**\n\n"
            )


def main():
    tests = discover_tests()

    generate_test_main(tests)
    generate_test_report(tests)

    print(f"Discovered {len(tests)} tests.")


if __name__ == "__main__":
    main()